### ISSUE TITLE
any plans to  add a bmp to raw converter to it8951usb?

### ISSUE THREAD

**Issue by MaBecker** [petrkr/it8951usb#3]
ImageMagick is a wonderful huge swiss  knife ;-) that needs more space than a raspberry pi or beagle bone like to give.

I am looking for this kind of use case:

1. app creates a bmp file on disk
2. who does the  bmp to byte array conversion?
3. it8951usb does the transfer

Any hints or tool recommendations?

**Comment by petrkr** [comment]
I think I will keep this library as-stupid-as-possible, so if you need some picture convert, it should be done by other software.  Like all unix/linux concept. Lot of smaller utilities (remember sed, awk, cat, etc...)

Because like this we can also add png, jpg, video etc later..

For now I trying learn how to do driver directly to Kernel-space and use FrameBuffer driver, which can do itself lot of stuff.. But I actually stuck on begin for example how to access SCSI device from kernelspace, because there you can not use same functions as here in user-space. So this code could be used only as inspiration for commands (for which I also have PDF documentation).

**Comment by petrkr** [comment]
I think convert from whatever to 8bit grayscale can be done also from python and from bitmap if you do not want use some done library then you can read it by binary and do math on pixels... (convert rgb to grayscale)

**Comment by MaBecker** [comment]
> I think I will keep this library as-stupid-as-possible,

Yes, I agree, keep it simple.

Will look for some npm modules or python stuff.
